# 生产环境配置 - 由部署脚本生成
watch_dir: /vol1/1000/projects 
snapshot_dir: /vol1/1000/snapshots
max_snapshots: 50
cleanup_mode: count
retention_days: 30
cooldown_seconds: 60
debounce_seconds: 10
log_file: /var/log/btrfs-snapshot-manager/snapshot.log
log_level: INFO
test_mode: false

# API服务配置
api:
  host: 0.0.0.0
  port: 5000
  debug: false
  cors_origins: ["*"]

# 安全配置
security:
  api_key_required: false
  max_snapshots_per_hour: 12

# 监控配置
monitoring:
  enable_metrics: true
  metrics_retention_hours: 72
