# 生产环境配置
watch_dir: /data/monitored        # 监控目录（可通过Web界面修改）
snapshot_dir: /data/snapshots     # 快照存储目录
max_snapshots: 50                 # 最大快照数量
cleanup_mode: count               # 清理模式: count 或 time
retention_days: 30                # 保留天数（time模式使用）
cooldown_seconds: 300             # 快照间隔冷却时间（5分钟）
debounce_seconds: 10              # 文件变化防抖时间
log_file: /app/logs/btrfs_snapshot.log
log_level: INFO
test_mode: false                  # 生产环境关闭测试模式

# API服务配置
api:
  host: 0.0.0.0
  port: 5000
  debug: false
  cors_origins: ["*"]             # 生产环境建议限制具体域名

# 安全配置
security:
  api_key_required: false         # 是否需要API密钥
  max_snapshots_per_hour: 12      # 每小时最大快照数限制

# 监控配置
monitoring:
  enable_metrics: true
  metrics_retention_hours: 72